package com.smartystreets.api

case class AddressComponents(urbanization: Option[String],
                             primaryNumber: Option[String],
                             streetName: Option[String],
                             streetPredirection: Option[String],
                             streetPostdirection: Option[String],
                             streetSuffix: Option[String],
                             secondaryNumber: Option[String],
                             secondaryDesignator: Option[String],
                             extraSecondaryNumber: Option[String],
                             extraSecondaryDesignator: Option[String],
                             pmbDesignator: Option[String],
                             pbmNumber: Option[String],
                             cityName: Option[String],
                             defaultCityName: Option[String],
                             stateAbbreviation: Option[String],
                             zipcode: Option[String],
                             plus4Code: Option[String],
                             deliveryPoint: Option[String],
                             deliveryPointCheckDigit: Option[String])