package com.smartystreets.api

case class AddressComponents(urbanization: Option[String],
                             primaryNumber: String,
                             streetName: String,
                             streetPredirection: Option[String],
                             streetPostdirection: Option[String],
                             streetSuffix: String,
                             secondaryNumber: Option[String],
                             secondaryDesignator: Option[String],
                             extraSecondaryNumber: Option[String],
                             extraSecondaryDesignator: Option[String],
                             pmbDesignator: Option[String],
                             pbmNumber: Option[String],
                             cityName: String,
                             defaultCityName: Option[String],
                             stateAbbreviation: String,
                             zipcode: String,
                             plus4Code: String,
                             deliveryPoint: String,
                             deliveryPointCheckDigit: String)