package com.smartystreets.api

case class AddressComponents(urbanization: Option[String],
                             primary_number: Option[String],
                             street_name: Option[String],
                             street_predirection: Option[String],
                             street_postdirection: Option[String],
                             street_suffix: Option[String],
                             secondary_number: Option[String],
                             secondary_designator: Option[String],
                             extra_secondary_number: Option[String],
                             extraSecondary_designator: Option[String],
                             pmb_designator: Option[String],
                             pbm_number: Option[String],
                             city_name: Option[String],
                             default_city_name: Option[String],
                             state_abbreviation: Option[String],
                             zipcode: Option[String],
                             plus4_code: Option[String],
                             delivery_point: Option[String],
                             delivery_point_check_digit: Option[String])